language: ruby
script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
env:
  - DEVISE_ORM=mongoid
  - DEVISE_ORM=active_record
matrix:
  exclude:
    - rvm: ree
      env: DEVISE_ORM=mongoid
      gemfile: Gemfile
    - rvm: ree
      env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 1.8.7
      env: DEVISE_ORM=mongoid
      gemfile: Gemfile
    - rvm: 1.8.7
      env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 1.9.2
      env: DEVISE_ORM=mongoid
      gemfile: Gemfile
    - rvm: 1.9.2
      env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-3.1.x
gemfile:
  - gemfiles/Gemfile.rails-3.1.x
  - Gemfile
services:
  - mongodb
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "TRiqvuM4i/QmRDWjUSNitE5/P91BOzDkNl53+bZjjtxcISCswZtmECWBR7n9\n3xwqCOU1o2lfohxZ32OHOj/Nj7o+90zWJfWxcv+if0hIXRiil62M5pg0lZUd\nyJ4M5VQ0lSWo5he1OUrXhSabPJeaK3B8yT/tdh+qO5yzR+vb/jc="
